# Custom dataset for object detection with safety helmets

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ./data/helmet/helmet/images/train
val: ./data/helmet/helmet/images/val

# number of classes
nc: 2

# class names
names: ['head', 'helmet']
