clients:
    # Type
    type: adaptive_freezing

    # The total number of clients
    total_clients: 1

    # The number of clients selected in each round
    per_round: 1

    # Should the clients compute test accuracy locally?
    do_test: true

server:
    address: localhost
    port: 8000

data:
    # The training and testing dataset
    datasource: MNIST

    # Where the dataset is located
    data_path: ./data

    # Number of samples in each partition
    partition_size: 20000

    # IID, biased, or sharded?
    divider: iid

    # Uniform or normal distribution for labels across clients?
    label_distribution: uniform

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 20

    # Whether the training should use multiple GPUs if available
    parallelized: false

    # The maximum number of clients running concurrently
    max_concurrency: 3

    # The target accuracy
    target_accuracy: 0.95

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 32
    optimizer: SGD
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0

    # The machine learning model
    model: lenet5

algorithm:
    # Aggregation algorithm
    type: adaptive_freezing

    # The initial synchronization frequency
    initial_sync_frequency: 100

    moving_average_alpha: 0.99
    stability_threshold: 0.05
    tight_threshold: 0.8
    random_freezing: true
