clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 3

    # The number of clients selected in each round
    per_round: 3

    # Should the clients compute test accuracy locally?
    do_test: true

server:
    address: localhost
    port: 8000

data:
    # The training and testing dataset
    dataset: MNIST

    # Where the dataset is located
    data_path: ./data

    # Number of samples in each partition
    partition_size: 20000

    # IID, biased, or sharded?
    divider: iid

    # Uniform or normal distribution for labels across clients?
    label_distribution: uniform

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 100

    # Whether the training should use multiple GPUs if available
    parallelized: false

    # The maximum number of clients running concurrently
    max_concurrency: 3

    # The target accuracy
    target_accuracy: 0.95

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 32
    optimizer: SGD
    learning_rate: 0.01
    momentum: 0.5
    weight_decay: 0.0

    # The machine learning model
    model: lenet5

algorithm:
    # Aggregation algorithm
    type: fedavg_cross_silo

    cross_silo:
        # The total number of silos (edge servers)
        total_silos: 2

        # The number of local aggregation rounds on edge servers before sending
        # aggreagted weights to the central server
        rounds: 2

results:
    # Write the following parameter(s) into a CSV
    types: accuracy, training_time, round_time, edge_agg_num

    # Plot results (x_axis&y_axis)
    plot: global_round&accuracy, global_round&training_time
