[tool.poetry]
name = "docs"
version = "0.1.0"
description = ""
authors = ["Baochun Li <bli@ece.toronto.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
Sphinx = "^5.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
