clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 100

    # The number of clients selected in each round
    per_round: 5

    # Should the clients compute test accuracy locally?
    do_test: true

    random_seed: 1

server:
    address: 127.0.0.1
    port: 8003
    do_test: false
    random_seed: 1

    checkpoint_path: /data/dixi/plato/models/fednasvit/cifar10_noniid/
    model_path: /data/dixi/plato/models/fednasvit/cifar10_noniid/
    # checkpoint_path: ../plato_models/fednasvit/cifar10_noniid/
    # model_path: ../plato_models/fednasvit/cifar10_noniid/

data:
    # The training and testing dataset
    datasource:  CIFAR10

    data_path: /data/dixi
    # data_path: ../data/

    # Number of samples in each partition
    partition_size: 600
    test_partition_size: 600

    sampler: noniid
##    # IID or non-IID?
##
##    # The concentration parameter for the Dirichlet distribution
    concentration: 0.3
##
    testset_sampler: noniid
##
##    # The random seed for sampling data
    random_seed: 1

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 1500

    # The maximum number of clients running concurrently
    max_concurrency: 3

    # The target accuracy
    target_accuracy: 0.99

    # Number of epochs for local training in each communication round
    epochs: 5
    batch_size: 32
    loss_criterion: CrossEntropyLoss
    optimizer: AdamW
    lr_scheduler: CosineAnnealingLR
    global_lr_scheduler: true

    model_name: nasvit

algorithm:
    # Aggregation algorithm
    type: fedavg
    
results:
    result_path: /data/dixi/plato/results/fednasvit/cifar10_noniid/
    # result_path: ../plato_results/fednasvit/cifar10_noniid/

parameters:
    model:
        num_classes: 10
        bn_momentum: 0.1
        bn_eps: 1e-5
        dropout: 0
        drop_connect: 0
    optimizer:
        lr: 0.0005
        eps: 1e-8
        betas: (0.9, 0.999)
        weight_decay: 0.0005
        momentum: 0.9
    # optimizer:
    #     lr: 0.05
    #     momentum: 0.9
    #     weight_decay: 0.0005
    # learning_rate:
    #     num_epochs: 360
    #     sched: cosine
    #     min_lr: 0.0005
    #     warmup_lr: 0.0000007
    #     warmup_epochs: 20
    #     cooldown_epochs: 0
    learning_rate:
        eta_min: 0.0002
        T_max: 7500
    architect:
        space: small
        # max_net: true
        # Darts lr: 0.0003 weight_decay 0.001
        # ProxyLessNas: 0.01 weight_decay: 0
        #FedRLNAS: 0.003 weight_dacey 0.0001
        learning_rate: 0.5
        weight_decay: 0
        baseline_decay: 0.9
        # pretrain_path: /data/dixi/plato/pretrained/nasvit/checkpoint.pth
        # pretrain_path: ../pretrained/ML_Models/nasvit/checkpoint.pth
